---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ LOG_VOLUME_NAME }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/conjur-log"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conjur-log-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
